### ISSUE TITLE
Credit yourself

### ISSUE THREAD

**Issue by kalina-ivanova** [getflourish/Sketch-Color-Contrast-Analyser#16]
I love your plugin and I use it all the time. I wanted to recommend it to someone and I noticed that there's no mention of your name or link to the repo in the Read.me file. I think you should credit yourself, you did an amazing job and deserve the recognition. ✌️

**Comment by getflourish** [comment]
@kalina-ivanova Thanks for the shout out. I really appreciate it and I’m happy that even 3 years later this plugin is still useful and working. I added the documentation URL to the plugin manifest, so that it is accessible from the Sketch Plugin Manager. I also added a note to the Readme.

**Comment by kalina-ivanova** [comment]
You're most welcome! It's one of my favorite plugins, keep up the great work. 😊
