### ISSUE TITLE
Hotkey support

### ISSUE THREAD

**Issue by fin85** [getflourish/Sketch-Color-Contrast-Analyser#18]
Hey, guys! I've checked out your cool plugin, it works perfectly! But here the thing, it's not so comfortable to make so many clicks to check contrast ratio - Plugins > Analyser. It would be great if you add a hotkey combination.

**Comment by getflourish** [comment]
Any suggestion for a shortcut? Unfortunately the potential for conflict is big with the sheer amount of plugins. I recommend to set up a custom shortcut that works well for you: https://medium.com/@jtaby/efficient-design-in-sketch-with-custom-keyboard-shortcuts-aec24d8f995
