### ISSUE TITLE
Incorrect font sizes used for checks

### ISSUE THREAD

**Issue by ZoeBijl** [getflourish/Sketch-Color-Contrast-Analyser#22]
From WCAG:

> large scale (text) with at least 18 point or 14 point bold or font size that would yield equivalent size for Chinese, Japanese and Korean (CJK) fonts

14 pt is equal to 18,667 pixels. Currently, this plugin threats 14 pt as 14 pixels; this is incorrect.

**Comment by monospaced** [comment]
@MichielBijl indeed, see #6 

I made a Pull Request to fix this issue https://github.com/getflourish/Sketch-Color-Contrast-Analyser/pull/21

@getflourish the fact that this plugin is falsly reporting that designs are WCAG 2.0 AA compliant should really be addressed.

**Comment by monospaced** [comment]
For reference, see this discussion:

https://github.com/w3c/wcag/issues/181

Which led to the addition of _Note 1__ here:

https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

Points do have potential for confusion, so WCAG now make it clear that 1pt = 1.333px, and therefore "large text" is approximately 24px or 18.5px bold.

**Comment by getflourish** [comment]
Thanks for pointing out the *Note 1* from the Spec. Thanks @monospaced for your effort of contributing and making the plugin accurate.

**Comment by getflourish** [comment]
Illustration of your finding here: https://codepen.io/getflourish/pen/oEyZRy

**Comment by monospaced** [comment]
@getflourish fantastic, thanks so much for addressing this! 👍

**Comment by equinusocio** [comment]
But, 18pt in sketch are 18px in css..
