### ISSUE TITLE
Plugin doesn't work with images

### ISSUE THREAD

**Issue by joshuamauldin** [getflourish/Sketch-Color-Contrast-Analyser#3]
If I put a text layer on top of an image, its contrast won't be properly analyzed. See this example where it says I have an acceptable contrast: 
![image](https://cloud.githubusercontent.com/assets/372017/6353878/e3a44756-bc19-11e4-9858-45c5ac847265.png)

**Comment by dustingoodman** [comment]
Text over an image does not need to pass contrast.

"Incidental: Text or images of text that are part of an inactive user interface component, that are pure decoration, that are not visible to anyone, or that are part of a picture that contains significant other visual content, have no contrast requirement."

http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html#user-interface-componentdef

I hope this helps.
