### ISSUE TITLE
Legacy Plugin

### ISSUE THREAD

**Issue by gmacpcguru** [getflourish/Sketch-Color-Contrast-Analyser#7]
This version of the plugin no longer works with Sketch (Version 3.8.3 (29802)) it displays as a legacy plugin. Please create a patch that will allow the plugin to work with the latest version of Sketch.

**Comment by nathanbiehl** [comment]
I have a working solution for 3.8+. @getflourish can you grant me write access to this repo so that I can commit a new branch?

**Comment by nathanbiehl** [comment]
@gmacpcguru plugin is now updated to work on 3.8+.
